### ISSUE TITLE
Dúvida Acerca Desvios Condicionais

### ISSUE THREAD

**Issue by GurgelAmaral** [karinaizo/Logica-de-Programacao#1]
Olá, você poderia me explicar como foi pensada a lógica do desvio condicional?

**Comment by karinaizo** [comment]
Boa tarde @GurgelAmaral ! Em qual exercício você gostaria que eu desse essa explicação?

**Comment by GurgelAmaral** [comment]
Exercício 5

**Comment by karinaizo** [comment]
@GurgelAmaral, eu recomendo [esse vídeo aqui](https://www.youtube.com/watch?v=_g05aHdBAEY). Caso você não consiga entender o exercício após assistir o vídeo estou aqui para tirar as dúvidas.

**Comment by karinaizo** [comment]
`html`
